version: '3.8'

services:
  app:
    build:
      context: ./routes
    ports:
      - "8888:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///tabres.db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432"

  alembic:
    build:
      context: .
      dockerfile: alembic.Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///tabres.db